name: unlimitednametags building

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: java 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: gradlew perms
      run: chmod +x gradlew

    - name: building
      run: ./gradlew build

    - name: uploadjar
      uses: actions/upload-artifact@v4
      with:
        name: UnlimitedNametags
        path: build/libs/*.jar
